name: ci

on:
  pull_request:
    types: [closed]

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: bendoerr-terraform-modules
          name: terraform-aws-fargate-on-demand-custodian
          token: ${{ github.token }}
          tag: pr-${{github.event.pull_request.number}}